import { reactive, computed } from 'vue'

const savedLanguage = typeof window !== 'undefined' ? localStorage.getItem('language') : null

export const state = reactive({
  language: savedLanguage || 'en'
})

const translations = {
  en: {
    brand: 'TEMBERA U RWANDA',
    home: 'Home',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    gallery: 'Gallery',
    photos: 'Photos',
    videos: 'Videos',
    destination: 'Destination',
    northern: 'Northern Province',
    southern: 'Southern Province',
    eastern: 'Eastern Province',
    kigali: 'Kigali City',
    western: 'Western Province',
    kinyarwanda: 'Kinyarwanda',
    french: 'French',
    footerQuickLinks: 'Quick Links',
    footerDestinations: 'Destinations',
    footerContact: 'Contact',
    footerCopyright: '@2026 Visit Rwanda',
    visitRwanda: 'Visit Rwanda',
    homeHero: 'Discover Rwanda\'s Hills, Culture, and Wild Beauty',
    homeSubtitle: 'From the misty slopes of Volcanoes National Park to the busy streets of Kigali, experience the heart of Africa in a fresh and welcoming way.',
    learnMore: 'Learn More',
    planYourTrip: 'Plan Your Trip',
    aboutHeroLabel: 'About Rwanda',
    aboutHeroTitle: 'A vibrant country built on resilience, nature, and hospitality',
    aboutHeroSubtitle: 'Rwanda is a place where ancient forests and modern cities meet, where every visitor can explore wildlife, culture, and community-led experiences with purpose and pride.',
    aboutStoryLabel: 'Our story',
    aboutStoryTitle: 'Welcome to a modern Rwanda with deep traditions',
    aboutStoryBody: 'Rwanda has rebuilt itself as one of Africa’s safest and most inspiring destinations. Visitors come for the gorilla trekking, but stay for the welcoming people, historic culture, and restored landscapes.',
    servicesHeroLabel: 'Our Services',
    servicesHeroTitle: 'Unforgettable Rwanda Experiences',
    servicesHeroBody: 'From mountain treks to cultural immersion, we craft personalized journeys that connect you with Rwanda’s natural beauty and vibrant communities.',
    servicesOfferLabel: 'What we offer',
    servicesTitle: 'Tailored Travel Services',
    servicesWhyTitle: 'Why Choose Our Services',
    servicesCTAHeading: 'Ready to Experience Rwanda?',
    servicesCTABody: 'Get in touch with us to plan your perfect Rwanda adventure. Our team is ready to help!',
    bookJourney: 'Book Your Journey',
    learnMoreAboutUs: 'Learn More About Us',
    contactGetInTouch: 'Get in touch',
    contactHeroTitle: 'Let’s plan your Rwanda adventure',
    contactHeroSubtitle: 'Tell us your travel interests and we’ll help match you with the best experiences in Kigali, the national parks, and beyond.',
    contactInfoLabel: 'Contact information',
    contactHelpTitle: 'We’re here to help',
    contactHelpBody: 'Reach out for travel advice, booking requests, or questions about our services in Rwanda. We respond quickly and can help design a custom itinerary to suit your needs.',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    locationLabel: 'Location',
    messageLabel: 'Message',
    sendButton: 'Send Message',
    galleryHeading: 'Welcome to Visit Rwanda Gallery',
    rwandaAtGlance: 'Rwanda at a glance',
    welcomeDestination: 'A welcoming destination for culture, nature, and adventure',
    exploreDescription: 'Explore national parks, local markets, lakeside retreats, and unforgettable experiences designed to connect you with Rwanda\'s people and landscapes.',
    whyChooseRwanda: 'Why choose Rwanda?',
    smallCountry: 'Small country, big experiences',
    gorillas: 'Gorillas and Green Hills',
    gorillasDesc: 'Track mountain gorillas, hike misty volcanoes, and find peace among Rwanda\'s lush hills and lakes.',
    cultureTitle: 'People and Traditions',
    cultureDesc: 'Meet local artisans, enjoy traditional dance, and discover stories from Rwanda\'s thriving communities.',
    cityLife: 'Kigali & modern hospitality',
    cityDesc: 'Discover Kigali\'s restaurants, galleries, and markets while enjoying warm service and comfortable stays.',
    rwandaAtGlance: 'Rwanda at a glance',
    welcomeDestination: 'A welcoming destination for culture, nature, and adventure',
    exploreDescription: 'Explore national parks, local markets, lakeside retreats, and unforgettable experiences designed to connect you with Rwanda\'s people and landscapes.',
    natureLabel: 'Nature',
    natureTitle: 'Gorillas and Green Hills',
    natureDesc: 'Track mountain gorillas, hike misty volcanoes, and find peace among Rwanda’s lush hills and lakes.',
    cultureLabel: 'Culture',
    cultureTitle: 'People and Traditions',
    cultureDesc: 'Meet local artisans, enjoy traditional dance, and discover stories from Rwanda’s thriving communities.',
    cityLifeLabel: 'City Life',
    cityLifeTitle: 'Kigali & modern hospitality',
    cityLifeDesc: 'Discover Kigali\'s restaurants, galleries, and markets while enjoying warm service and comfortable stays.',
    whyChooseRwanda: 'Why choose Rwanda?',
    smallCountry: 'Small country, big experiences',
    safeAccessibleTitle: 'Safe and accessible',
    safeAccessibleDesc: 'Rwanda is known for clean cities, welcoming people, and well-maintained national parks.',
    richWildlifeTitle: 'Rich wildlife',
    richWildlifeDesc: 'See gorillas, golden monkeys, hippos, and dozens of bird species on guided nature tours.',
    meaningfulTravelTitle: 'Meaningful travel',
    meaningfulTravelDesc: 'Support local communities and enjoy authentic experiences rooted in Rwandan culture.',
    aboutVisionTitle: 'Vision',
    aboutVisionBody: 'Share Rwanda’s natural and cultural wonders through sustainable travel.',
    aboutMissionTitle: 'Mission',
    aboutMissionBody: 'Create unforgettable journeys that support communities and protect wildlife.',
    aboutSpecialTitle: 'What makes Rwanda special',
    aboutSpecialItem1Title: 'Gorilla Conservation',
    aboutSpecialItem1Body: 'A global leader in protecting mountain gorillas and their forest home.',
    aboutSpecialItem2Title: 'Cultural Renewal',
    aboutSpecialItem2Body: 'Rich arts, music, and storytelling rooted in Rwandan heritage.',
    aboutSpecialItem3Title: 'Scenic Journeys',
    aboutSpecialItem3Body: 'Rolling hills, lakes, and forest trails that invite exploration.',
    aboutExperienceLabel: 'Experience',
    aboutExperienceTitle: 'A journey shaped by people and place',
    aboutExperienceBody: 'Whether you want a luxury lodge stay, a cultural village visit, or a life-changing wildlife trek, Rwanda welcomes you with thoughtful hospitality and breathtaking scenery.',
    wildlifeToursTitle: 'Wildlife Tours',
    wildlifeToursBody: 'Experience mountain gorilla trekking, golden monkey visits, and bird watching in Rwanda\'s pristine national parks with expert guides.',
    wildlifeToursItem1: 'Volcanoes National Park treks',
    wildlifeToursItem2: 'Nyungwe Forest explorations',
    wildlifeToursItem3: 'Akagera wildlife safaris',
    culturalImmersionTitle: 'Cultural Immersion',
    culturalImmersionBody: 'Connect with local communities, learn traditional crafts, enjoy authentic cuisine, and experience Rwandan hospitality firsthand.',
    culturalImmersionItem1: 'Village homestays',
    culturalImmersionItem2: 'Traditional craft workshops',
    culturalImmersionItem3: 'Local market visits',
    adventureActivitiesTitle: 'Adventure Activities',
    adventureActivitiesBody: 'Hiking, kayaking, and outdoor adventures through Rwanda\'s stunning landscapes and scenic lake regions.',
    adventureActivitiesItem1: 'Mountain hiking expeditions',
    adventureActivitiesItem2: 'Lake Kivu kayaking',
    adventureActivitiesItem3: 'Nature trail walks',
    cityToursTitle: 'Kigali City Tours',
    cityToursBody: 'Explore Rwanda\'s vibrant capital city, visit historical sites, museums, markets, restaurants, and contemporary art galleries.',
    cityToursItem1: 'Genocide Memorial visits',
    cityToursItem2: 'Museum & gallery tours',
    cityToursItem3: 'Restaurant & nightlife',
    luxuryRetreatsTitle: 'Luxury Retreats',
    luxuryRetreatsBody: 'Enjoy comfort and elegance at premium lodges and resorts with world-class amenities and stunning views.',
    luxuryRetreatsItem1: 'Boutique lodge stays',
    luxuryRetreatsItem2: 'Spa & wellness services',
    luxuryRetreatsItem3: 'Fine dining experiences',
    customPackagesTitle: 'Custom Packages',
    customPackagesBody: 'Let us design your perfect Rwanda itinerary tailored to your interests, budget, and travel timeline.',
    customPackagesItem1: 'Personalized itineraries',
    customPackagesItem2: 'Group packages',
    customPackagesItem3: 'Corporate retreats',
    serviceGuidesTitle: 'Expert Guides',
    serviceExpertGuides: 'Local experts with deep knowledge of Rwanda\'s culture and nature',
    serviceValueTitle: 'Best Value',
    serviceBestValue: 'Competitive pricing without compromising on quality',
    serviceSustainableTitle: 'Sustainable',
    serviceSustainable: 'Eco-friendly practices that support local communities',
    serviceSupportTitle: 'Support',
    serviceSupport: 'Round-the-clock customer service for your peace of mind'
  },
  rw: {
    brand: 'TEMBERA U RWANDA',
    home: 'Ahabanza',
    about: 'Ibyerekeye',
    services: 'Serivisi',
    contact: 'Tuvugane',
    gallery: 'Amafoto',
    photos: 'Amafoto',
    videos: 'Amashusho',
    destination: 'Aho ujya',
    northern: 'Amajyaruguru',
    southern: 'Amajyepfo',
    eastern: 'Uburasirazuba',
    kigali: 'Kigali',
    western: 'Uburengerazuba',
    kinyarwanda: 'Kinyarwanda',
    french: 'Igifaransa',
    footerQuickLinks: 'Imiyoboro',
    footerDestinations: 'Ahantu',
    footerContact: 'Twandikire',
    footerCopyright: '@2026 Tembera Rwanda',
    visitRwanda: 'Tembera U Rwanda',
    homeHero: 'Kubona Inzira, Amasantu, n\'Ubwenge bwa Rwanda',
    homeSubtitle: 'Kuva mu buhoti bw\'isi mpuzamahanga kugeza mu muhanda w\'Itorero w\'Ineza, ubona umuntu mu mahoro ya Afrika muli mwaka mwiza.',
    learnMore: 'Menya Neza',
    planYourTrip: 'Shyiramo Igihigo',
    aboutHeroLabel: 'Ibyerekeye u Rwanda',
    aboutHeroTitle: 'Igihugu cyikoreye gifite imbaraga, kamere, n’ubukerarugendo',
    aboutHeroSubtitle: 'U Rwanda ni ahantu aho amashyamba ya kera n’imijyi ya none bihurira, aho buri mucumbitsi ashobora gusura inyamaswa, umuco, n’uburambe bwubatswe n’umuryango.',
    aboutStoryLabel: 'Inkuru yacu',
    aboutStoryTitle: 'Murakaza neza mu Rwanda rw’ubu rwubakiye ku muco ukomeye',
    aboutStoryBody: 'U Rwanda rwiyubuye nk’igihugu kimwe mu bifite umutekano muri Afurika. Abashyitsi baza kubera ingendo z’ingagi, ariko basigara kubera abantu bakwakira, umuco w’amateka, n’imisozi yongewe gusubirwamo.',
    servicesHeroLabel: 'Serivisi zacu',
    servicesHeroTitle: 'Ubuzima budasanzwe mu Rwanda',
    servicesHeroBody: 'Uhereye mu ngendo z’imisozi kugeza mu muco, dukora ingendo zihariye zihuza nawe n’akamaro k’umutungo kamere w’u Rwanda n’imiryango yaho.',
    servicesOfferLabel: 'Ibyo dutanga',
    servicesTitle: 'Serivisi zateguwe',
    servicesWhyTitle: 'Kuki wahitamo serivisi zacu',
    servicesCTAHeading: 'Witeguye gutembera u Rwanda?',
    servicesCTABody: 'Twandikire kugirango dushyireho urugendo rwawe rwiza rwo mu Rwanda. Itsinda ryacu rihari kugira ngo rigufashe!',
    bookJourney: 'Bika urugendo rwawe',
    learnMoreAboutUs: 'Menya byinshi kuri twebwe',
    contactGetInTouch: 'Twandikire',
    contactHeroTitle: 'Dutegure urugendo rwawe rwo mu Rwanda',
    contactHeroSubtitle: 'Tubwira ibyo wifuza mu rugendo maze tukaguhitiramo ibyiza bijyanye na Kigali, pariki mpuzamahanga, n’ahandi.',
    contactInfoLabel: 'Amakuru yo kuvugana',
    contactHelpTitle: 'Turi hano kugufasha',
    contactHelpBody: 'Twandikire ku nama z’urugendo, gusaba gahunda, cyangwa ibibazo ku serivisi zacu mu Rwanda. Dusubiza vuba kandi dushobora gufasha gutegura gahunda ikwiranye n’ibyo ukeneye.',
    emailLabel: 'Imeyili',
    phoneLabel: 'Telefoni',
    locationLabel: 'Aho turi',
    messageLabel: 'Ubutumwa',
    sendButton: 'Ohereza Ubutumwa',
    galleryHeading: 'Murakaza neza mu bubiko bw’amafoto y’u Rwanda',
    rwandaAtGlance: 'U Rwanda mu buryo bwihuse',
    welcomeDestination: 'Aho mwakinirije amasantu, ubwenge, n\'ubushake bw\'imivyezo',
    exploreDescription: 'Kubona imbere z\'igihugu, iparike z\'abaturage, ibarunga ry\'amazi, n\'imivyezo itubera ibibazo kandi turambuke mu mahoro ya Rwanda.',
    whyChooseRwanda: 'Kuki Wahitamo Rwanda?',
    smallCountry: 'Igihugu gito, ibyiza byinshi',
    gorillas: 'Ingagi n\'Inzira Ziruta',
    gorillasDesc: 'Kumurikira ingagi z\'imbwa, guhikira umusozi w\'ishuti, kandi gukunzira mu mahoro yo mumurwanya.',
    cultureTitle: 'Abaturage n\'Amasantu',
    cultureDesc: 'Kuvugana n\'abandi bamwe, kwakira indirimbo y\'igihugu, kandi kumenya inkuru z\'u Rwanda.',
    cityLifeLabel: 'Ubwiyunge bwa Kigali',
    cityLifeTitle: 'Kigali no Ubwiyunge bw\'Igihugu',
    cityLifeDesc: 'Kubona ibitotsi bya Kigali, igikeri cy\'umwuga, n\'amasoko mu mahoro yo mumarayuzi neza.',
    natureLabel: 'Umutungo kamere',
    natureTitle: 'Ingagi n\'Inzira Ziruta',
    natureDesc: 'Kumurikira ingagi z\'imbwa, guhikira umusozi w\'ishuti, kandi gukunzira mu mahoro yo mumurwanya.',
    cultureLabel: 'Umuco',
    cityLife: 'Kigali no Ubwiyunge bw\'Igihugu',
    cityDesc: 'Kubona ibitotsi bya Kigali, igikeri cy\'umwuga, n\'amasoko mu mahoro yo mumarayuzi neza.',
    safeAccessibleTitle: 'Umutekano n\'ubwiyunge',
    safeAccessibleDesc: 'U Rwanda witiriwe mu butekano bwayo, abaturage bakwakira, n\'iparike zacu zirambye neza.',
    richWildlifeTitle: 'Inyamaswa nyinshi',
    richWildlifeDesc: 'Reba ingagi, inzira y\'ibinyamabanga, n\'ubwoko bwinshi bw\'inyoni mu magezi y\'abanyarugendo.',
    meaningfulTravelTitle: 'Urugendo rwiza',
    meaningfulTravelDesc: 'Funga imiryango n\'ubona ubwenge bwakozwe mu muco w\'u Rwanda.',
    aboutVisionTitle: 'Igihigo',
    aboutVisionBody: 'Gutanga ubwenge bw\'u Rwanda ubwato n\'umuco bacu.',
    aboutMissionTitle: 'Inzira',
    aboutMissionBody: 'Gukora ingendo zidasanzwe zishyiga imiryango n\'inyamaswa.',
    aboutSpecialTitle: 'Ibyo gituma Rwanda gitandukanye',
    aboutSpecialItem1Title: 'Kubungabunga ingagi',
    aboutSpecialItem1Body: 'U Rwanda ni umvano mu ntambara zo kubungabunga ingagi.',
    aboutSpecialItem2Title: 'Umuco n\'ubuhanzi',
    aboutSpecialItem2Body: 'Ubuhanzi, indirimbo, n\'inzira z\'igihugu cy\'u Rwanda.',
    aboutSpecialItem3Title: 'Ingendo n\'imisozi',
    aboutSpecialItem3Body: 'Imisozi, amazi, n\'inzira z\'amashyamba ishaka gusuburwa.',
    aboutExperienceLabel: 'Ubuzima',
    aboutExperienceTitle: 'Urugendo rwubakiyemo abantu n\'aho turi',
    aboutExperienceBody: 'Ubwifuza ubwiyunge bwiza, gucukuma umuco, cyangwa kunzira ingagi, u Rwanda wakunzira n\'ubwiyunge bukomeye n\'ibyikiro bidasanzwe.',
    wildlifeToursTitle: 'Ingendo z\'inyamaswa',
    wildlifeToursBody: 'Reba ingagi z\'imbwa, inzira y\'ibinyamabanga, n\'ubwoko bwinshi bw\'inyoni mu magezi y\'abanyarugendo.',
    wildlifeToursItem1: 'Ingendo z\'iparike y\'umusozi w\'ishuti',
    wildlifeToursItem2: 'Kubona amashyamba ya Nyungwe',
    wildlifeToursItem3: 'Ingendo z\'inyamaswa mu Akagera',
    culturalImmersionTitle: 'Ubwenge bw\'umuco',
    culturalImmersionBody: 'Vugana n\'imiryango, menya ikoranabuhoro, kandi ubona ubwiyunge bw\'u Rwanda.',
    culturalImmersionItem1: 'Guhagarika mu nda z\'abantu',
    culturalImmersionItem2: 'Amahoro yo kwigisha ikoranabuhoro',
    culturalImmersionItem3: 'Imbaga y\'abapiritari',
    adventureActivitiesTitle: 'Imivyezo y\'ubushake',
    adventureActivitiesBody: 'Guhikira, kweta mu nyanja, n\'imivyezo y\'isi mu mateka y\'u Rwanda.',
    adventureActivitiesItem1: 'Ingendo z\'guhikira',
    adventureActivitiesItem2: 'Kweta mu gitara Kivu',
    adventureActivitiesItem3: 'Ingendo z\'inzira y\'amashyamba',
    cityToursTitle: 'Ingendo z\'Umujyi wa Kigali',
    cityToursBody: 'Reba umujyi wa Kigali, iyimidugudu y\'amateka, isiteri z\'ubwenge, n\'amasoko.',
    cityToursItem1: 'Iyimidugudu y\'amahoro y\'ubwiyunge',
    cityToursItem2: 'Ubwiyunge bwa isiteri n\'imidugudu y\'ubuhanzi',
    cityToursItem3: 'Ibyo duryamo n\'ubuharanira bushakiro',
    luxuryRetreatsTitle: 'Ubwiyunge bwiza cyane',
    luxuryRetreatsBody: 'Injoya n\'ubwiyunge mu nda nziza cyane hamwe n\'ibyoroshye byanyu.',
    luxuryRetreatsItem1: 'Guhagarika mu nda nziza',
    luxuryRetreatsItem2: 'Ikibazo n\'ubwiyunge',
    luxuryRetreatsItem3: 'Ibyo duryamo byiza cyane',
    customPackagesTitle: 'Gahunda z\'ihariye',
    customPackagesBody: 'Tubaho gahunda yawe ikwiranye n\'ibyo wifuza, amafaranga yayo, n\'igihe cyo rugendo.',
    customPackagesItem1: 'Gahunda z\'ihariye',
    customPackagesItem2: 'Gahunda z\'itsinda',
    customPackagesItem3: 'Gahunda z\'isosiyete',
    serviceGuidesTitle: 'Abanyarugendo ba mugezi',
    serviceExpertGuides: 'Abaturage ba mugezi bifite ubwenge bw\'u Rwanda',
    serviceValueTitle: 'Ubwiyunge bwiza',
    serviceBestValue: 'Ibikoresho nubwiyunge bukunzira',
    serviceSustainableTitle: 'Ubwiyunge bushaka igihugu',
    serviceSustainable: 'Imikoresho itubera igihugu n\'imiryango',
    serviceSupportTitle: 'Ubufasha',
    serviceSupport: 'Ubufasha buhoraho kugirango ubwiyunge bwawe buri neza'
  },
  fr: {
    brand: 'TEMBERA U RWANDA',
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    contact: 'Contact',
    gallery: 'Galerie',
    photos: 'Photos',
    videos: 'Vidéos',
    destination: 'Destination',
    northern: 'Province Nord',
    southern: 'Province Sud',
    eastern: 'Province Est',
    kigali: 'Kigali',
    western: 'Province Ouest',
    kinyarwanda: 'Kinyarwanda',
    french: 'Français',
    footerQuickLinks: 'Liens Rapides',
    footerDestinations: 'Destinations',
    footerContact: 'Contact',
    footerCopyright: '@2026 Visitez le Rwanda',
    visitRwanda: 'Visitez le Rwanda',
    homeHero: 'Découvrez les collines, la culture et la beauté sauvage du Rwanda',
    homeSubtitle: 'Des pentes brumeuses du Parc National des Volcans aux rues animées de Kigali, découvrez le cœur de l\'Afrique d\'une manière nouvelle et accueillante.',
    learnMore: 'En savoir plus',
    planYourTrip: 'Planifier votre voyage',
    aboutHeroLabel: 'À propos du Rwanda',
    aboutHeroTitle: 'Un pays dynamique forgé par la résilience, la nature et l’hospitalité',
    aboutHeroSubtitle: 'Le Rwanda est un lieu où les forêts anciennes et les villes modernes se rencontrent, où chaque visiteur peut explorer la faune, la culture et des expériences communautaires porteuses de sens et de fierté.',
    aboutStoryLabel: 'Notre histoire',
    aboutStoryTitle: 'Bienvenue au Rwanda moderne aux traditions profondes',
    aboutStoryBody: 'Le Rwanda s’est reconstruit en tant que l’une des destinations les plus sûres et les plus inspirantes d’Afrique. Les visiteurs viennent pour le trekking des gorilles, mais restent pour le peuple accueillant, la culture historique et les paysages restaurés.',
    servicesHeroLabel: 'Nos Services',
    servicesHeroTitle: 'Des expériences inoubliables au Rwanda',
    servicesHeroBody: 'Des randonnées en montagne à l’immersion culturelle, nous créons des voyages personnalisés qui vous connectent à la beauté naturelle du Rwanda et à ses communautés dynamiques.',
    servicesOfferLabel: 'Ce que nous proposons',
    servicesTitle: 'Services sur mesure',
    servicesWhyTitle: 'Pourquoi choisir nos services',
    servicesCTAHeading: 'Prêt à découvrir le Rwanda?',
    servicesCTABody: 'Contactez-nous pour planifier votre aventure parfaite au Rwanda. Notre équipe est prête à vous aider !',
    bookJourney: 'Réserver votre voyage',
    learnMoreAboutUs: 'En savoir plus sur nous',
    contactGetInTouch: 'Contactez-nous',
    contactHeroTitle: 'Planifions votre aventure au Rwanda',
    contactHeroSubtitle: 'Dites-nous vos intérêts de voyage et nous vous aiderons à trouver les meilleures expériences à Kigali, dans les parcs nationaux et au-delà.',
    contactInfoLabel: 'Informations de contact',
    contactHelpTitle: 'Nous sommes là pour vous aider',
    contactHelpBody: 'Contactez-nous pour des conseils de voyage, des demandes de réservation ou des questions sur nos services au Rwanda. Nous répondons rapidement et pouvons aider à concevoir un itinéraire personnalisé adapté à vos besoins.',
    emailLabel: 'Email',
    phoneLabel: 'Téléphone',
    locationLabel: 'Emplacement',
    messageLabel: 'Message',
    sendButton: 'Envoyer le message',
    galleryHeading: 'Bienvenue dans la galerie Visit Rwanda',
    rwandaAtGlance: 'Le Rwanda en un coup d\'œil',
    welcomeDestination: 'Une destination accueillante pour la culture, la nature et l\'aventure',
    exploreDescription: 'Explorez les parcs nationaux, les marchés locaux, les retraites au bord du lac et les expériences inoubliables conçues pour vous connecter avec le peuple et les paysages du Rwanda.',
    whyChooseRwanda: 'Pourquoi choisir le Rwanda?',
    smallCountry: 'Petit pays, grandes expériences',
    gorillas: 'Gorilles et collines verdoyantes',
    gorillasDesc: 'Suivez les gorilles des montagnes, randonnez sur les volcans brumeux et trouvez la paix parmi les collines luxuriantes et les lacs du Rwanda.',
    cultureTitle: 'Peuple et traditions',
    cultureDesc: 'Rencontrez les artisans locaux, profitez de la danse traditionnelle et découvrez les histoires des communautés dynamiques du Rwanda.',
    cityLifeLabel: 'Vie urbaine',
    cityLifeTitle: 'Kigali et hospitalité moderne',
    cityLifeDesc: 'Découvrez les restaurants, galeries et marchés de Kigali tout en profitant d\'un service chaleureux et de séjours confortables.',
    natureLabel: 'Nature',
    natureTitle: 'Gorilles et collines verdoyantes',
    natureDesc: 'Suivez les gorilles des montagnes, randonnez sur les volcans brumeux et trouvez la paix parmi les collines luxuriantes et les lacs du Rwanda.',
    cultureLabel: 'Culture',
    cityLife: 'Kigali et hospitalité moderne',
    cityDesc: 'Découvrez les restaurants, galeries et marchés de Kigali tout en profitant d\'un service chaleureux et de séjours confortables.',
    safeAccessibleTitle: 'Sûr et accessible',
    safeAccessibleDesc: 'Le Rwanda est connu pour ses villes propres, ses habitants accueillants et ses parcs nationaux bien entretenus.',
    richWildlifeTitle: 'Riche faune',
    richWildlifeDesc: 'Voyez des gorilles, des singes dorés, des hippopotames et des dizaines d\'espèces d\'oiseaux lors de visites naturelles guidées.',
    meaningfulTravelTitle: 'Voyage significatif',
    meaningfulTravelDesc: 'Soutenez les communautés locales et profitez d\'expériences authentiques enracinées dans la culture rwandaise.',
    aboutVisionTitle: 'Vision',
    aboutVisionBody: 'Partager les merveilles naturelles et culturelles du Rwanda grâce aux voyages durables.',
    aboutMissionTitle: 'Mission',
    aboutMissionBody: 'Créer des voyages inoubliables qui soutiennent les communautés et protègent la faune.',
    aboutSpecialTitle: 'Ce qui rend le Rwanda spécial',
    aboutSpecialItem1Title: 'Conservation des gorilles',
    aboutSpecialItem1Body: 'Leader mondial dans la protection des gorilles des montagnes et de leur forêt.',
    aboutSpecialItem2Title: 'Renouveau culturel',
    aboutSpecialItem2Body: 'Arts riches, musique et histoires enracinées dans l\'héritage rwandais.',
    aboutSpecialItem3Title: 'Voyages pittoresques',
    aboutSpecialItem3Body: 'Collines ondulantes, lacs et sentiers forestiers qui invitent à l\'exploration.',
    aboutExperienceLabel: 'Expérience',
    aboutExperienceTitle: 'Un voyage façonné par les gens et le lieu',
    aboutExperienceBody: 'Que vous désiriez un séjour à un lodge de luxe, une visite dans un village culturel ou un trek faunique qui change la vie, le Rwanda vous accueille avec une hospitalité réfléchie et des paysages à couper le souffle.',
    wildlifeToursTitle: 'Circuits fauniques',
    wildlifeToursBody: 'Découvrez le trekking des gorilles des montagnes, les visites des singes dorés et l\'observation des oiseaux dans les parcs nationaux vierges du Rwanda avec des guides experts.',
    wildlifeToursItem1: 'Treks du Parc National des Volcans',
    wildlifeToursItem2: 'Explorations de la forêt de Nyungwe',
    wildlifeToursItem3: 'Safaris fauniques d\'Akagera',
    culturalImmersionTitle: 'Immersion culturelle',
    culturalImmersionBody: 'Connectez-vous avec les communautés locales, apprenez les métiers traditionnels, dégustez la cuisine authentique et vivez l\'hospitalité rwandaise de première main.',
    culturalImmersionItem1: 'Séjours en famille d\'accueil',
    culturalImmersionItem2: 'Ateliers d\'artisanat traditionnel',
    culturalImmersionItem3: 'Visites de marché local',
    adventureActivitiesTitle: 'Activités d\'aventure',
    adventureActivitiesBody: 'Randonnée, kayak et aventures en plein air à travers les paysages spectaculaires et les régions de lacs pittoresques du Rwanda.',
    adventureActivitiesItem1: 'Expéditions de randonnée en montagne',
    adventureActivitiesItem2: 'Kayak sur le lac Kivu',
    adventureActivitiesItem3: 'Promenades sur les sentiers naturels',
    cityToursTitle: 'Visites de la ville de Kigali',
    cityToursBody: 'Explorez la capitale dynamique du Rwanda, visitez des sites historiques, des musées, des marchés, des restaurants et des galeries d\'art contemporain.',
    cityToursItem1: 'Visites du mémorial du génocide',
    cityToursItem2: 'Visites de musées et galeries',
    cityToursItem3: 'Restaurants et vie nocturne',
    luxuryRetreatsTitle: 'Retraites de luxe',
    luxuryRetreatsBody: 'Profitez du confort et de l\'élégance dans les lodges haut de gamme et les resorts avec des équipements de classe mondiale et des vues époustouflantes.',
    luxuryRetreatsItem1: 'Séjours en lodge boutique',
    luxuryRetreatsItem2: 'Services de spa et bien-être',
    luxuryRetreatsItem3: 'Expériences de gastronomie fine',
    customPackagesTitle: 'Forfaits personnalisés',
    customPackagesBody: 'Laissez-nous concevoir l\'itinéraire parfait du Rwanda adapté à vos intérêts, votre budget et votre calendrier de voyage.',
    customPackagesItem1: 'Itinéraires personnalisés',
    customPackagesItem2: 'Forfaits de groupe',
    customPackagesItem3: 'Retraites d\'entreprise',
    serviceGuidesTitle: 'Guides experts',
    serviceExpertGuides: 'Des experts locaux ayant une connaissance approfondie de la culture et de la nature du Rwanda',
    serviceValueTitle: 'Meilleur prix',
    serviceBestValue: 'Tarifs compétitifs sans compromettre la qualité',
    serviceSustainableTitle: 'Durable',
    serviceSustainable: 'Pratiques respectueuses de l\'environnement qui soutiennent les communautés locales',
    serviceSupportTitle: 'Support',
    serviceSupport: 'Service clientèle 24h/24 pour votre tranquillité d\'esprit'
  }
}

export const current = computed(() => ({
  ...translations.en,
  ...(translations[state.language] || {})
}))

export const setLanguage = (lang) => {
  state.language = lang
  if (typeof window !== 'undefined') {
    localStorage.setItem('language', lang)
  }
}
